'use strict';
// GENERATED by `npm run hashes` (scripts/update-default-hashes.js) — do not edit by hand, and
// never delete entries. See that script's header for why.

export const SHIPPED_DEFAULT_HASHES: { [fileName: string]: string[] } = {
    'css.tmpl': [
        '44dd8e3a136f8c007b2d1dfef7c33d257a1cc8bcd1a1bc2ac813ccf51e45bf31',
        '2cb8b29a608e7a961e9f8efc992822f868b3b3b46d91745c2e94f1c091bf16b4'
    ],
    'html.tmpl': [
        '0e8f519efa640e61aa0dd63da829c039f074c991a7c57f5e61c65cfb27585b70'
    ],
    'javascript.tmpl': [
        '26ffd68764a2fead8154c5a0712004ab081c9d7a2751b23217dae718e56587e9',
        'b22b2b10618c92b00978ee0e2b875bc98f3c323432d1fc0213b4c126206b008d'
    ],
    'javascriptreact.tmpl': [
        '26ffd68764a2fead8154c5a0712004ab081c9d7a2751b23217dae718e56587e9',
        'b22b2b10618c92b00978ee0e2b875bc98f3c323432d1fc0213b4c126206b008d'
    ],
    'php.tmpl': [
        '911476ef195e0eb5b21681d09c868296a37824646174bbf1256a85bfafaecfa4',
        '1c7c05ea1e564dcdbecbd0e4d7b8f938f71e18f6260c338f16c62a1c18e2c6bf'
    ],
    'python.tmpl': [
        'b98562f3438378f48ae005d26abad01105d9f5bc9d1b858a1b6ada62096325f9',
        '34e136341023e898bcbabce4246db53b5264b02bfbb21b7e3c37f01deee17836'
    ],
    'ruby.tmpl': [
        '5560ddb15bb7c84ba3716001dfe93aa7c416f1849d0920b04bedc697d872b2e0'
    ],
    'typescript.tmpl': [
        '26ffd68764a2fead8154c5a0712004ab081c9d7a2751b23217dae718e56587e9',
        'b22b2b10618c92b00978ee0e2b875bc98f3c323432d1fc0213b4c126206b008d'
    ],
    'typescriptreact.tmpl': [
        '26ffd68764a2fead8154c5a0712004ab081c9d7a2751b23217dae718e56587e9',
        'b22b2b10618c92b00978ee0e2b875bc98f3c323432d1fc0213b4c126206b008d'
    ],
    'vue.tmpl': [
        '313fc5b6165c34d9981ac1e0b71ea23be9ec093990cc637edba4bb0ee48de63c',
        '4d170f761f77a259e938a35914e3d2ad9db5c0d6adc7798ba58aabbd67994cd6'
    ],
    'xml.tmpl': [
        '4dbe1cec7805b3b8795f869e493758c94a6453d6d44f4de6d16c4c4c94713f4d'
    ]
};
